---
title: "RandomForest_Prediction"
author: "Gabriel Yarleque"
date: "5/4/2020"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc_depth: 5
    toc: yes
vignette: >
  %\VignetteIndexEntry{RandomForest_Prediction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "~/external/data/")
knitr::opts_chunk$set(echo = TRUE)

```


```{r, eval= FALSE}
############################################################################

#Install libraries
library(sf)
# install.packages("randomForest")
require(randomForest)
library(dplyr)
# install.packages("caTools")
library(caTools)
library(raster)
library(rgdal)
library(geospaar)
library(leaflet)
```


# Random Forest Regression

```{r, error = TRUE, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 4, fig.align = 'center'}
##############################   Random Forest Regression at 2500###############################

# Data reading

path_out <- '../inst/extdata'


DS <- read.csv('../inst/extdata/Imperv_connect_Struct_Traffic_NDSI.csv', header = T) 


# Filter values using 2500 as the scale of best influence
DS_2500 <- DS %>% filter(Buffer == "Buffer 2500 (m)") %>% dplyr::select(-c(Buffer, SiteName, Biophony, Anthrophony)) %>% rename("Connectedness" = Connectdness)

# Scale variable values except NDSI values 
DS_2500_scaled <- DS_2500[,1:4]/255

# Use mutate to add NDSI values back to the table. 
DS_2500_scaled <- DS_2500_scaled %>% mutate("NDSI" = DS_2500$NDSI)

# Create training and testing samples
sample = caTools::sample.split(DS_2500$NDSI, SplitRatio = .75)
train = subset(DS_2500, sample == TRUE)
test  = subset(DS_2500, sample == FALSE)

# Check out the dimensions of each sample set
dim(train)
dim(test)

# Create RandomForest Model
set.seed(100)
rf_2500 <- randomForest::randomForest(NDSI ~., data=DS_2500_scaled, mtry= 2, importance = TRUE, na.action=na.omit)

print(rf_2500)

# Show "importance" of variables: higher value means more important:
round(importance(rf_2500), 2)

# Visualize Variable Importance Plot
randomForest::varImpPlot(rf_2500, main = "Variable Importance at 2500 buffer level")
```


# Predictive Modeling 

```{r, error = TRUE, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 4, fig.align = 'center'}
# Read raster images for imperviousness, connectedness, structure, and traffic
          
# fslc <- dir("../inst/extdata", pattern = "lc2500*.tif", full.names = TRUE)

          
Imperv <- raster("../inst/extdata/lc2500_imperv.tif")
Connectedness <- raster("../inst/extdata/lc2500_connect.tif")
Structure <- raster("../inst/extdata/lc2500_structure.tif")
Traffic <- raster("../inst/extdata/lc2500_traffic.tif")

# Create a raster stack
landcover_ls <- list(Imperv, Connectedness, Structure, Traffic)
names(landcover_ls) <- c("Imperv", "Connectedness", "Structure", "Traffic")

my_stack <- stack(landcover_ls)
# Use raster::predict to predict NDSI values across the landscape
ndsi_pred <- raster::predict(object = my_stack, model=rf_2500, type = 'response', index = 5)
ndsi_pred

# Plot NDSI prediction layer 
plot(ndsi_pred)

# Display NDSI prediction layer with sample locations. First, set the CRS for the sampling locations to match the one from the raster image

sites <- st_read(dsn = "../inst/extdata/sample_sites_projected.shp")
sites <- st_transform(x = sites, crs = st_crs(ndsi_pred))

geospaar::plot_noaxes(ndsi_pred, main = "NDSI Prediction")
plot(st_geometry(sites), add = TRUE)

# Plot variables and predicted NDSI raster image

# Rename ndsi_pred
names(ndsi_pred) <- c("NDSI_Prediction")

stack_final <- stack(my_stack,ndsi_pred)
geospaar::plot_noaxes(stack_final)


pal2 <- colorNumeric(c("#F2F2F2FF","#EEB99FFF", "#EAB64EFF","#E6E600FF","#00A600FF"), values(ndsi_pred), na.color = "transparent")
pal3 <- colorNumeric(c("#00A600FF","#E6E600FF","#EAB64EFF","#EEB99FFF","#F2F2F2FF"), values(ndsi_pred), na.color = "transparent")

leaflet() %>% addTiles() %>% addCircleMarkers(lng = sites$Long, lat = sites$Lat, weight = 1, popup = sites$Site) %>% 
  addRasterImage(ndsi_pred, colors = pal2, opacity = 0.8) %>%
  addLegend(pal = pal3, values = values(ndsi_pred), labFormat = labelFormat(transform = function(x) sort(x, decreasing = TRUE)),title = "Surface temp")




```


